--insert into user (userid, active, email, last_name, name, password) values (1, 1, 'abc@test.com', 'nair', 'megha', 'password');
--insert into card (cardid, balance, cardcode, email) values (12345, 10, 789, 1);
--insert into card (cardid, balance, cardcode, email) values (123456, 8, 781, 1);
--insert into starbucks_order (order_id, bill_amount, user_id) values (2, 5, 1);
--insert into starbucks_order (order_id, bill_amount, user_id) values (3, 6, 1);